# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce6e549338c94d4693c9138930e921270e19fa9e0de8c0b60c82313d0a7eff6ed3892cac5d57a5cf630ac450b06f51e2b5169b117f112506d8e985934dd6ab5

test:
  secret_key_base: dbbbe42b3cb13351ae7f335591c23ec092d72b0863eca7c6b401dfb08ade6fecc961b2ccbac9b3ced6546c16309882456ae68516834ea53acae098e2e086a9c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
